all:
  vars:
    ansible_user: vagrant
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
prod:
  hosts:
    client1:
      ansible_host: 10.10.20.1
  vars:
    ansible_ssh_password: vagrant
    env: production
