---
- name: Deploy AWS EC2
  hosts: localhost
  become_user: vagrant
  vars:
    ansible_connection: local
  vars_files:
    - group_vars/all.yml
    - group_vars/secret.yml
  roles:
    - geerlingguy.pip
    - deploy-ec2
  tags:
    - ec2

- name: Deploy Webapp
  hosts: "{{ host_group_name }}"
  become: true
  remote_user: ec2-user
  vars:
    - docker_users:
      - ec2-user
  vars_files:
    - group_vars/all.yml
    - group_vars/secret.yml
  roles:
    - geerlingguy.docker
    - geerlingguy.repo-epel
    - deploy-webapp
  tags:
    - webapp