---
- name: Deploy AWS EC2
  hosts: localhost
  become: true
  vars:
    ansible_connection: local
  vars_files:
    - group_vars/all.yml
    - group_vars/secret.yml
  roles:
    - deploy-ec2
  tags:
    - ec2

- name: Deploy Webapp
  hosts: "{{ host_group_name }}"
  #become: true
  become_user: ec2-user
  vars:
    ansible_connection: local
  vars_files:
    - group_vars/all.yml
    - group_vars/secret.yml
  roles:
    - geerlingguy.pip
    - geerlingguy.docker
    - deploy-ec2
  tags:
    - webapp