---
- name: Deploy apache with docker on targeted hosts
  hosts: prod
  become: yes

  pre_tasks:
    - name: Install EPEL repo
      package: 
        name: epel-release 
        state: present
      when: ansible_distribution == "CentOS"

    - name: Download pip script
      get_url:
        url: https://bootstrap.pypa.io/pip/2.7/get-pip.py
        dest: /tmp/get-pip.py

    - name: Install python-pip
      command: python2.7 /tmp/get-pip.py

    - name: Install docker-python
      pip:
        name: docker-py

    - name: Install pre-requisites to install docker
      yum:
        name: 
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
        state: latest

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
      become: yes

    - name: Enable Docker Edge repo
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-edge'
        option: enabled
        value: 0

    - name: Enable Docker Test repo
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-test'
        option: enabled
        value: 0
    
    - name: Install Docker
      package:
        name: docker-ce
        state: latest

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add user vagrant to docker group
      user:
        name: vagrant
        groups: docker
        append: yes
    
   # - name: Install ansible-lint
   #   pip:
   #     name: ansible-lint
   #     state: latest

  tasks:
    - name: Create Apache container
      docker_container:
        name: webapp
        image: httpd
        ports: 
          - "80:80"
      tags:
      - start_container

    - name: Stop docker container
      command: docker rm -f webapp
      tags:
      - stop_container

