---
# tasks file for deploy-webapp
- name: Install packages
  include_tasks: packages.yml

- name: Create Apache container
  become_user: ec2-user
  #become: true
  docker_container:
    name: webapp
    image: httpd
    ports:
      - "80:{{ PORT_CONTAINER }}"
