---
# Tasks to install pre-requisites
- name: download pip script
  get_url:
    url: https://bootstrap.pypa.io/pip/2.7/get-pip.py
    dest: /tmp/get-pip.py

- name: install python-pip
  command: python /tmp/get-pip.py

- name: Install docker python
  become_user: ec2-user
  pip: name=docker-py