---
- name: "Apache installation using Docker"
  hosts: prod
  become: yes
  pre_tasks:
  - name: Install EPEL repo
    yum:
      name: epel-release
      state: present
    when: ansible_distribution == "CentOS"
  - name: Install python-pip
    yum:
      name: python-pip 
      state: present
      update_cache: yes
  tasks:
  - name: Install docker python
    pip:
      name: docker-py
  - name: Create apache container
    docker_container:
      name: webapp
      image: httpd
      ports:
      - 80:80
